CREATE TABLE IF NOT EXISTS `worksheets` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `installation_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `address` varchar(255) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `has_visit` tinyint(1) DEFAULT 0,
  `visitor_name` varchar(255) DEFAULT NULL,
  `house_type` varchar(100) DEFAULT NULL,
  `aluminum1` varchar(100) DEFAULT NULL,
  `length_count1` int(11) DEFAULT 1,
  `aluminum2` varchar(100) DEFAULT NULL,
  `length_count2` int(11) DEFAULT 1,
  `support_type` varchar(100) DEFAULT NULL,
  `electric_panel` varchar(100) DEFAULT NULL,
  `has_panel_space` tinyint(1) DEFAULT 1,
  `basement` varchar(255) DEFAULT NULL,
  `installation_type` varchar(100) DEFAULT NULL,
  `sub_installation_type` varchar(100) DEFAULT NULL,
  `particularities` json DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `installation_id` (`installation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; 